### PR TITLE
Implement scss

### PR DESCRIPTION
**Pull request by larsdesigns**
Converting css to scss.

### CODE REVIEW

**Comment by larsdesigns** [comment]
This needs to be tested on a working application.

**Comment by pkiraly** [comment]
Dear @larsdesigns, could you please 
1. create an issue ticket for this PR
2. add a note to that ticket or this PR how to use scss in the current technology stack
I am not familiar with SCSS, as far as I know it requires some interpreter to generate CSS out of it. If that is true, we have some consequences, such as set up such an interpreter, make sure that the generated CSS is not conflicting with the existing CSS, we should decide which version we will maintain in the future.

**Comment by nichtich** [comment]
Can this be closed? SCSS has good use cases, but for this project it adds more complexity for little benefit.

**Comment by pkiraly** [comment]
@larsdesigns Would you like to work on this? If not we will close this PR, bacuase of the unanswered questions, and the concerns mentioned by @nichtich.

**Comment by pkiraly** [comment]
Since there is no progress and @larsdesigns did not reply, I close this pull request. We can reopen this topic later.

**Comment by larsdesigns** [comment]
@pkiraly, My apologies for I was not receiving the notification from this thread. I would be happy to work further on this. SCSS is a way to manage CSS and keep it simplified. It has minimal requirements and can be installed using these instructions: https://sass-lang.com/install/. 

However, due to recent advancements in CSS such as nesting (https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting/Using_CSS_nesting) and variables (https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties), I predict scss/sass is on the way to be phased out.

So, I can agree with the decision to close this issue.

**Comment by pkiraly** [comment]
@larsdesigns Do you have an overview how these new CSS features are supported by the browsers? For example nesting seems to be not a W3C development, at least Mozilla's document provides a link to https://drafts.csswg.org/css-nesting-1/ as the specification, however it is a draft, and less than 2 month old. That document say that the latest published version is available at https://www.w3.org/TR/css-nesting-1/ - and it is a bit older, created 14 February 2023. Sorry, I do not follow the development of the CSS, so any feedback on the browser support and release plans would be useful.

**Comment by larsdesigns** [comment]
It looks like variables are well supported: https://www.w3schools.com/css/css3_variables.asp
and it looks like nesting is somewhat supported but in variations by the three top browsers: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting/Using_CSS_nesting, https://webkit.org/blog/13813/try-css-nesting-today-in-safari-technology-preview/ and https://developer.chrome.com/docs/css-ui/css-nesting. Yes, as you pointed out it looks like the W3C still has the specification and module in draft: https://www.w3.org/TR/css-nesting-1/. 

So, it looks like SASS/SCSS or LESS CSS https://lesscss.org is the still preferred. I already rewrote most of the styles using SCSS so that would be a good jumpstart. 

It does add a some complexity but SASS is easy to install and produce css without JavaScript tools like gulp.

**Comment by pkiraly** [comment]
@larsdesigns A question: do SASS/SCSS or LESS CSS work this way:
- it needs a "compiler" software
- it takes a specially format input
- it produces pure css 
?
If that is true, then the developers need the compiler, but it is not needed for running the website. Could you confirm these?

**Comment by pkiraly** [comment]
@larsdesigns 
> Would you like me to continue implementing scss?
Sorry for the delayed reply: yes, it would be great!

**Comment by larsdesigns** [comment]
@pkiraly, I am thinking this is a good technique to use https://symfony.com/doc/6.4/the-fast-track/en/22-encore.html.

**Comment by nichtich** [comment]
If the CSS is generated from SCSS than the CSS files become build artifacts to be *removed* from the source code repository. Please also add documentation how to build the CSS from SCSS.

**Comment by pkiraly** [comment]
@larsdesigns It is not clear for me if you refer to Webpack, Webpack Encore or Symfony as a good technique? When I started this project I tried Symfony, and I decided not to use it because its templating engine Twig as I missed important features from it that I like in Smarty templating engine. As far as I understand Webpack bundles and minifies the CSS output of SASS.

@nichtich What we should solve is two tasks: 

1. the developers should be able to run the CSS generation process 
2. the non developers should be able to install the application without installing npm. 

Maybe I am wrong but if we remove the generated CSS from the project the second requirement will fail, unless we automatically generate a downloadable package that contains the CSS-es (such as the Dockerized version) and ask people not to use the git clone process.

**Comment by larsdesigns** [comment]
Ah, okay. I noticed composer and remembered it as a Symfony app. I will just work on the scss.

**Comment by pkiraly** [comment]
Yes, it is using composer, and I would like to have more composer components in the future and less custom code. I like several things in Symfony, and I plan to investigate for example if Router and HTTP request/response management could be put to QA Catalogue from Symfony, so if you find a component that is available in Packagist, feel free to make a suggestion to include.

**Pull request closed without merging**
