### PR TITLE
create startup page

### PR DESCRIPTION
**Pull request by NelDav**

### CODE REVIEW

**Comment by nichtich** [comment]
By now the completeness tab is shown by default. I also welcome to show another tab with faster loading time than completeness (we have more then 70 million records).

**Comment by pkiraly** [comment]
I have merged the changes into a new branch, `qa-catalogue-web`. Could you create a pull request against that branch? In the Github UI I do not see any option to change the target branch from my side.

**Comment by NelDav** [comment]
> @NelDav I have merged the changes into a new branch, `create-startup-page`. Could you create a pull request against that branch? In the Github UI I do not see any option to change the target branch from my side.

I am not completely sure, if that is what you want, but this PR will merge into [pkiraly:create-startup-page](https://github.com/pkiraly/qa-catalogue-web/tree/create-startup-page) now.

**Comment by NelDav** [comment]
> See related pull request #102
> 
> I'd not call it "start" because the start page should be configurable (#106) but maybe "overview" or "summary".



> By now the completeness tab is shown by default. I also welcome to show another tab with faster loading time than completeness (we have more then 70 million records).

I think that is one goal of this feature, to reduce the loading time of the start page.

> I'd not call it "start" because the start page should be configurable (https://github.com/pkiraly/qa-catalogue-web/issues/106) but maybe "overview" or "summary".

I do not know, why somebody would prefer to use a detailed view as start page, but I also do not really care about the name of this start/overview/summary page.
@pkiraly What name do you prefer?

**Comment by pkiraly** [comment]
@nichtich Some background information: the reason of this development is to create a "dashboard" page which contains some smaller, but expressive charts which compress the most important quality indicators, so the user can have a full impression of what's goind on from a single page. David works on it as his master project at computer science, so this is an experimental feature. You are right that we should call it in a name which concentrates on the content, and not necessary "start page".

**Comment by NelDav** [comment]
@pkiraly Am I supposed to continue the work on the pkiraly:start-up-page branch now? If that is the case, I would delete this branch.

**Pull request merged**
