### PR TITLE
Implemention of a Dashboard

### PR DESCRIPTION
**Pull request by NelDav**
This is the implementation of a dashboard that presents some charts, giving an overview about the data:

image

### CODE REVIEW

**Comment by NelDav** [comment]
I finished the implementation of some suggestions from the survey and do not plan to change more things.
However, if you @pkiraly want to change some little things, before merging, we can discuss them here.

**Comment by pkiraly** [comment]
Thanks a lot!

**Review by pkiraly — COMMENTED** [review]
You changed quite number of things. I hope it will work, only from the source code it is really hard to judge. Many thanks again!

**Comment by pkiraly** [comment]
Dear @NelDav, 

Thank you so much for your work!

I would like to see one change, which I can not decide if it is a small one or not. Please decide it, and tell me if it is over the limits, it is not a problem at all.

In the opening state of completeness the Y-axis shows IDs created by the QA catalogue, that is not part of the MARC21 standard. In the UI at the Completeness tab it is not shows. Instead I would like to see 00X, 01x-09X etc. as it is in the completeness tab:

Screenshot from 2023-11-11 17-22-38

Would it be feasible?

**Comment by NelDav** [comment]
Is there a map, that is able to translate the numbers, presented on the y-axis to the correct labels?

**Comment by NelDav** [comment]
I found a translation. I think it should be possible.

**Comment by NelDav** [comment]
It is done. I accidentally pushed it to the main branch. I hope that does not bother you too much.

**Pull request merged**
